export const TRAITS = [
    { name: "Kill Securer", image: "/images/kill-securer.jpg", description: "" },
    { name: "The Conqueror", image: "/images/conquer.jpg", description: "" },
    { name: "Glass Cannon", image: "/images/glass-cannon.webp", description: "" },
    { name: "The Warden", image: "/images/ward.png", description: "" },
    { name: "Yuumi’s Yuumi", image: "/images/yuumi.jpg", description: "" },
    { name: "Pocket Support", image: "/images/pocket-support.jpg", description: "" },
    { name: "Retail Therapy", image: "/images/ping.png", description: "" },
    { name: "Cash Cow", image: "/images/generational-wealth.jpg", description: "" },
    { name: "KDA Player", image: "/images/kda.png", description: "" },
    { name: "The One-Trick Pony", image: "/images/one-trick.jpg", description: "" },
    { name: "Flex Master", image: "/images/flex.jpg", description: "" },
    { name: "Singleplayer Only", image: "/images/solo.jpg", description: "" },
    { name: "Potential Man", image: "/images/potential-man.jpg", description: "" },
    { name: "Snowball Fighter", image: "/images/snowball.jpg", description: "" },
    { name: "The Staller Supreme", image: "/images/stall.jpg", description: "" },
    { name: "Monkey D. Luffy", image: "/images/luffy.jpg", description: "" },
    { name: "Rage Quitter", image: "/images/rage-quitter.png", description: "" },
];